{ ... }:

{
  imports = [
    ./agenix.nix
    ./atuin.nix
    ./bottom.nix
    ./clac
    ./cli.nix
    ./dark-theme.nix
    ./direnv.nix
    ./discord.nix
    ./dwm
    ./feh.nix
    ./file-roller.nix
    ./firefox.nix
    ./flameshot.nix
    ./games.nix
    ./gammastep.nix
    ./git.nix
    ./gromit-mpx.nix
    ./gui.nix
    ./hm.nix
    ./java.nix
    ./latex.nix
    ./lf
    ./lsp
    ./matlab.nix
    ./mpv.nix
    ./nix.nix
    ./nvim
    ./onlyoffice.nix
    ./piper.nix
    ./polkit.nix
    ./python.nix
    ./rofi.nix
    ./sdk.nix
    ./sound.nix
    ./ssh.nix
    ./starship.nix
    ./tmux.nix
    ./virtualisation.nix
    ./vscode.nix
    ./wireshark.nix
    ./xfce4-terminal.nix
    ./zathura.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
