{ ... }:

{
  imports = [
    ./agenix.nix
    ./atuin.nix
    ./bottom.nix
    ./chatgpt.nix
    ./clac
    ./cli.nix
    ./dark-theme.nix
    ./desktop.nix
    ./direnv.nix
    ./discord.nix
    ./dwm
    ./dwm-status.nix
    ./feh.nix
    ./file-roller.nix
    ./firefox.nix
    ./flameshot.nix
    ./fonts.nix
    ./games.nix
    ./gammastep.nix
    ./git.nix
    ./gromit-mpx.nix
    ./gui.nix
    ./hm.nix
    ./java.nix
    ./latex.nix
    ./lf
    ./light.nix
    ./lsp.nix
    ./matlab.nix
    ./mpv.nix
    ./nix.nix
    ./nvim
    ./onlyoffice.nix
    ./opentabletdriver.nix
    ./piper.nix
    ./polkit.nix
    ./python.nix
    ./rofi.nix
    ./sdk.nix
    ./sound.nix
    ./ssh.nix
    ./starship.nix
    ./system.nix
    ./tmux.nix
    ./virtualisation.nix
    ./vscode.nix
    ./wireshark.nix
    ./xfce4-terminal.nix
    ./xserver.nix
    ./zathura.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
