keys:
  - &geppc-host age1feczrstdxexwaa23m6wpyy74g7t06ehm7yjsq7j92gk68utwtvmq5k4a7n
  - &geptop-xmg-host age1gjv0dnpuuh05f8pdsz0pk2t3vjxrtpwvyk69h2damwr473ztpals96nxvc
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *geppc-host
        - *geptop-xmg-host
